const routes = {
  home: '/',
  signIn: '/login',
  register: '/register',
  logout: '/logout',
  productdetails: '/products/:title/:id',
  search: '/search/:title',
  cart: '/cart',
  cat: '/cat',
  404: '*',

  // users needs to login
  profile: '/user/account/profile',
  purchaseOrder: '/user/account/purchase',
  address: '/user/account/address',
  changePassword: '/user/account/change_password',
  bank: '/user/account/bank',
  notification: '/user/account/notification',
  voucher: '/user/account/voucher',
  userbank: '/user/account/bank',
};

export const adminRoutes = {
  Logo: '/admin/logo',
  AddLogo: '/admin/add-logo',
  SignIn: '/admin/login',
  ResetPassword: '/admin/reset-pass',
  Home: '/admin',
  ProfileAdmin: '/admin/profile',
  ChangePassword: '/admin/change-password',
  AllAdmin: '/admin/admin',
  EditAdmin: '/admin/edit-admin/:id',
  AddAdmin: '/admin/add-admin',
  AllUser: '/admin/user',
  EditUser: '/admin/edit-user/:id',
  AllShop: '/admin/shop',
  EditShop: '/admin/edit-shop/:id',
  Location: '/admin/location',
  Category: '/admin/category',
  Blogs: '/admin/blogs',
  EditBlogs: '/admin/edit-blogs/:id',
  AddBlogs: '/admin/add-blogs',
  Department: '/admin/department',
  OrderProduct: '/admin/order',
  AllProduct: '/admin/product',
  EditProduct: '/admin/edit-product/:id',
  ReportProduct: '/admin/report-product',
  Voucher: '/admin/voucher',
  AddVoucher: '/admin/add-voucher',
  EditVoucher: '/admin/edit-voucher/:id',
  Manufacturer: '/admin/manufacturer',
  AddManufacturer: '/admin/add-manufacturer',
  EditManufacturer: '/admin/edit-manufacturer/:id',
  Role: '/admin/role',
  [404]: '/admin/*',
};

export const ShopSeller = {
  SignUp: '/seller/register',
  SignIn: '/seller/login',
  LinkResetPass: '/seller/password/reset-password',
  ResetPass: '/seller/password/reset',
  ChangePassword: '/seller/change-password',
  Home: '/seller',
  VerifiedEmail: '/seller/verify-email',
  RegisterShop: '/seller/register-shop',
  [404]: '/seller/*',

  /*setting shop */
  SettingIdentityInfo: '/seller/shop/setting/identity-info',
  SettingTaxInfo: '/seller/shop/setting/tax-info',
  SettingBasicInfo: 'seller/shop/setting/basic-info',
  SettingShopInfo: '/seller/shop/setting/shop-info',
  SettingNotification: '/seller/shop/all-settings/notification',
  SettingAccount: '/seller/shop/all-settings/account',
  SettingShippingAddress: '/seller/shop/all-settings/shipping/address-management',
  SettingShippingChannel: '/seller/shop/all-settings/shipping/shipping-channel',
  SettingShippingDocument: '/seller/shop/all-settings/shipping/shipping-document',
  SettingPayment: '/seller/shop/all-settings/payment',
  SettingChat: '/seller/shop/all-settings/chat',
  SettingVacationMode: '/seller/shop/all-settings/vacation-mode',
  SettingPartnerManagement: '/seller/shop/all-settings/partner-management',

  /*notification*/
  Notification: '/seller/shop/notification',
  NotificationOrder: '/seller/shop/notification/order-updates',
  NotificationRating: '/seller/shop/notification/rating-updates',
  NotificationReturnRefund: '/seller/shop/notification/return-refund',
  NotificationProduct: '/seller/shop/notification/listing-updates',
  NotificationWallet: '/seller/shop/notification/wallet-updates',
  NotificationLifeShop: '/seller/shop/notification/lifeshop-updates',

  /* management order */
  ManagementOrder: '/seller/shop/sale/order',
  ManagementShipment: '/seller/shop/sale/shipment',
  ManagementOrderMassShipment: '/seller/shop/sale/mass/ship',
  ManagementReturnRefund: '/seller/shop/sale/return',

  /* product */
  // Product: '/seller/shop/product/new',
  NewProduct: '/seller/shop/product/new',
  AllProduct: '/seller/shop/product/all-product',

  /* management chat */
  CSKH: '/seller/shop/cskh',
  CSKHManagementChat: '/seller/shop/cskh/management-chat',
  CSKHManagementRating: '/seller/shop/cskh/management-rating',

  /* finance & data center */
  Finance: '/seller/shop/finance',
  FinanceIncome: '/seller/shop/finance/income',
  FinanceWalletLifePay: '/seller/shop/finance/wallet/life-pay',
  FinanceWalletCards: '/seller/shop/finance/wallet/cards',

  DataCenter: '/seller/shop/data-center/overview',
  DataCenterProduct: '/seller/shop/data-center/product/overview',
  DataCenterProductPerfomance: '/seller/shop/data-center/product/perfomance',
  DataCenterProductDiagnosis: '/seller/shop/data-center/product/diagnosis',
  DataCenterSales: '/seller/shop/data-center/sales/overview',
  DataCenterSalesComposition: '/seller/shop/data-center/sales/composition',
  DataCenterServices: '/seller/shop/data-center/services/overview',
  DataCenterServicesFAQ: '/seller/shop/data-center/services/faq',
  DataCenterTraffic: '/seller/shop/data-center/traffic/overview',
  DataCenterTrafficOffPlatform: '/seller/shop/data-center/traffic/off-platform',
  DataCenterMarketingDiscount: '/seller/shop/data-center/marketing/discount',
  DataCenterMarketingFlashSales: '/seller/shop/data-center/marketing/flash-sales',
  DataCenterMarketingVoucher: '/seller/shop/data-center/marketing/voucher',
  DataCenterMarketingLifeLive: '/seller/shop/data-center/marketing/livestream',
  DataCenterMarketingPrize: '/seller/shop/data-center/marketing/game',
  DataCenterSalesMasterTrending: '/seller/shop/data-center/selling/trending',
  DataCenterSalesMasterCompete: '/seller/shop/data-center/selling/similar',
  DataCenterSalesMasterTopKeyword: '/seller/shop/data-center/selling/top-keywords',

  DataCenterAccountHealth: '/seller/shop/data-center/accounthealth/home',
  DataCenterAccountHealthImprove: '/seller/shop/data-center/accounthealth/issues',
  DataCenterAccountHealthProductLock: '/seller/shop/data-center/accounthealth/p-lock',
  DataCenterAccountHealthOrderFails: '/seller/shop/data-center/accounthealth/metric-detail',
  DataCenterAccountHealthTimePrepare: '/seller/shop/data-center/accounthealth/pt',
  DataCenterAccountHealthPreOrder: '/seller/shop/data-center/accounthealth/pod',
  DataCenterAccountHealthViolation: '/seller/shop/data-center/accounthealth/violation',
  DataCenterAccountHealthRatioResponse: '/seller/shop/data-center/accounthealth/rr',
  DataCenterAccountHealthTimeResponse: '/seller/shop/data-center/accounthealth/rt',
  DataCenterAccountHealthRateShop: '/seller/shop/data-center/accounthealth/rs',
  DataCenterAccountHealthPreferredSeller: '/seller/shop/data-center/accounthealth/preferred-seller',
  DataCenterAccountHealthPenalty: '/seller/shop/data-center/accounthealth/penalty',

  /*marketing */
  Marketing: '/seller/shop/marketing',
  MarketingShopDiscount: '/seller/shop/marketing/list/discount',
  MarketingShopFLashSale: '/seller/shop/marketing/shop-flash-sale/list',
  MarketingShopVoucher: '/seller/shop/marketing/voucher',
  MarketingShopAdvertising: '/seller/shop/marketing/advertising',
  MarketingShopNewVoucher: '/seller/shop/marketing/voucher/new',
  MarketingShopCampaign: '/seller/shop/marketing/campaign',
};

export default routes;
